services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ai-hackathon-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/app:/app/app:ro
    restart: unless-stopped

  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai-hackathon-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    env_file:
      - frontend/.env
    restart: unless-stopped
